### PR TITLE
Remove unused `jl_stdout_obj` import since it was removed in Julia 1.11

### LINKED ISSUE #234: juliacall fails in julia 1.11 with `undefined symbol: jl_stdout_obj`
Hi there, I just tried out julia 1.11 because it has support for caching compile files.
Unfortunately R-JuliaCall fails with some problems. Trying to replicate it in a mwe, I found this incompatbility.

```juliarepl
julia> import Pkg; Pkg.add("CondaPkg")

julia> using CondaPkg

julia> CondaPkg.add("r"); CondaPkg.add("r-juliacall")

julia> envdir = CondaPkg.envdir()
"/root/.julia/environments/v1.11/.CondaPkg/env"

julia> localpreferences = """
       [RCall]
       Rhome = "$envdir/lib/R"
       libR = "$envdir/lib/R/lib/libR.so"
       """

julia> write(joinpath(dirname(Base.active_project()), "LocalPreferences.toml"), localpreferences)

julia> import Pkg; Pkg.add("RCall")

julia> using RCall

julia> reval("""
       library(JuliaCall)
       julia_setup(installJulia=TRUE)
       """)
┌ Warning: CHOLMOD version incompatibility
│ 
│ Julia was compiled with CHOLMOD version 4.0.4. It is
│ currently linked with version 5.2.1.
│ This might cause Julia to terminate when working with
│ sparse matrix factorizations, e.g. solving systems of
│ equations with \.
│ 
│ It is recommended that you use Julia with the same major
│ version of CHOLMOD as the one used during the build, or
│ download the generic binaries from www.julialang.org,
│ which ship with the correct versions of all dependencies.
└ @ SparseArrays.CHOLMOD ~/.julia/environments/v1.11/.CondaPkg/env/share/julia/stdlib/v1.10/SparseArrays/src/solvers/cholmod.jl:206
Segmentation fault (core dumped)
``` 

----------

restarting julia after this segmenation fault and running the below, gives another error:

```juliarepl
julia> using RCall

julia> reval("""
       library(JuliaCall)
       julia_setup(installJulia=TRUE)
       """)
ERROR: REvalError: Julia version 1.11.0-rc3 at location /usr/local/julia/bin will be used.
Error: jl_stdout_obj - /usr/local/julia/bin/../lib/libjulia.so.1.11: undefined symbol: jl_stdout_obj
```

### PR DESCRIPTION
**Pull request by JackDunnNZ**
This `jl_stdout_obj` doesn't seem to be used anywhere in the package, and was removed in Julia 1.11: https://github.com/JuliaLang/julia/pull/53250

Fixes #234

### CODE REVIEW

**Comment by schlichtanders** [comment]
Looking forward to get this merged! Currently RCall blocks me from transitioning to Julia 1.11

**Comment by schlichtanders** [comment]
@JackDunnNZ thank you for you work. What is needed to get this merged? I am really blocked by this and would like to speed up the process if possible

**Comment by cderv** [comment]
I believe we are all in wait of 
- #208 
And a discussion on what to do next should happen there. 

Other PR like #210 are opened since more than 1 year with no reaction.

**Comment by PallHaraldsson** [comment]
bump.

If this wasn't actually used, can't this be speedily merged? And presumably solving the problem (on master; and then tag a new version?).

**Comment by JackDunnNZ** [comment]
> bump.
> 
> If this wasn't actually used, can't this be speedily merged? And presumably solving the problem (on master; and then tag a new version?).

Please read the issue linked above, @Non-Contradiction is unfortunately nowhere to be found

**Comment by PallHaraldsson** [comment]
I did and I realize @Non-Contradiction is absent, maybe only one(?) with merge access. I would be willing to fix this (get maintainer status), I see you @JackDunnNZ have some commits, presumably no access (nor any other contributor), why I also edited, mentioning my alternative at JulaLang.

**Comment by JackDunnNZ** [comment]
Yes, unfortunately I have no commit access - I am merely an invested user that fixes things each time they have broken :)

**Comment by fingolfin** [comment]
There are other potential issues with this package. E.g. for some reason it doesn't seem to use the official Julia C headers, instead copying bits of it. This is inherently dangerous and fragile. I note that they copied a definition for struct `jl_module_t`. This definition is not matching the actual definition anymore. This *may* be OK (if they don't actually try to access any of the members of this struct), but overall I really wonder why this approach was chosen.

**Comment by PallHaraldsson** [comment]
My alternative fix, partial revert in JuliaLang has been approved (by you), though not yet merged.

It makes this PR redundant, and I believe fixes that package (for now).

Given that the package is doing something "inherently dangerous and fragile" it could break again later in 1.12+.

There's no way to take over a GitHub project (unless people die, maybe), wouldn't be a good policy. But in Julia registry there is I think a way to take over a project pointing to a forked project.

I don't know how things are handled in R, I'm a bit ignorant, is there some official procedure in case of maintainer disappearing?

**Comment by ViralBShah** [comment]
Do people have commit access here? Perhaps this package should live in JuliaInterop and recruit a larger pool of maintainers?

**Comment by PallHaraldsson** [comment]
Apparently nobody has commit access here, or the one or few that do are not listening (for 3+ days).

I agree this could live in JuliaInterop (at least if R users would look there, or get linked there), that would mean forking it, but I'm thinking, in R community, would it still link here? Even changing docs is not possible (here) like only works in 1.11.2 (after my PR merged), and I'm not sure where R people get this from if not directly from Github, or what docs they would see.

**Comment by ViralBShah** [comment]
I have emailed @Non-Contradiction requesting transfer to JuliaInterop.

**Comment by Non-Contradiction** [comment]
Dear all, thank you very much. After consideration, I agree with @ViralBShah and will transfer the package to JuliaInterop. I once granted commit access to some people. But it seems that they are busy too. It seems that transftering the package to JuliaInterop will allow a broader pool of maintainers and is the right choice.

**Comment by Non-Contradiction** [comment]
I agree that not using Julia's official header is dangerous and fragile. 
It really was an ad hoc approach in the early days of JuliaCall.
On the R side, every C code compilation must happen at the package installation stage, otherwise compilation will happen every time at the loading of the package (which is very slow and intolerable, especially in the early days....).  
Then JuliaCall basically needs to have Julia's official header with it.  And also JuliaCall needed to consider that user may have different versions of Julia instead of a single version to use with JuliaCall. So I tried to use a minimal subset of header to avoid the conflicting between versions and yet have a functional package.  But this approach is really fragile, and the existence of this issue proves exactly this.

**Comment by ViralBShah** [comment]
@Non-Contradiction I have given you owner access on JuliaInterop to move the package. Once you move, I will reduce the permission level but still make sure you have full access to your package.

Thanks for the explanation. I understand the challenge better, and others may be better suited to chime in on what can be done to improve things.

**Comment by schlichtanders** [comment]
The package is transferred. Awesome :rocket: . 

Looking forward to have r-JuliaCall ready for julia 1.11 soon

**Comment by ViralBShah** [comment]
Should this PR be merged? Who else can help here - I am happy to add them to have commit access.

**Comment by ChrisRackauckas** [comment]
It's a bit scary since it looks like the CI didn't run. Someone who knows how to fix R CI should probably make sure to fix that and so something runs, and merge this if it passes?

**Comment by JackDunnNZ** [comment]
Not sure why it's not running here, but I resynced this branch to master and the CI passed on my repo (except for R-devel)

https://github.com/JackDunnNZ/JuliaCall/actions/runs/11719241531

**Comment by ChrisRackauckas** [comment]
I'll need to be added as a maintainer on CRAN though in order to do a new CRAN release.

**Comment by JackDunnNZ** [comment]
I found this: https://stackoverflow.com/a/78334023

It looks like basically the new maintainer needs to proceed with a release, and @Non-Contradiction will receive an email to confirm the change

**Comment by Non-Contradiction** [comment]
Thanks everyone! If everything is ready, then I am very happy to make a new release on CRAN. Just @ me or email me when any thing is needed to be done on my side.

**Comment by bachmeil** [comment]
In case anyone else is hitting this error:

```
Error: jl_stdout_obj - /home/office/.julia/juliaup/julia-1.11.1+0.x64.linux.gnu/bin/../lib/libjulia.so.1.11: undefined symbol: jl_stdout_obj
```

You'll need to install from the repo until the CRAN package is updated:

```
library(devtools)
install_github("https://github.com/JuliaInterop/JuliaCall")
```

**Comment by ViralBShah** [comment]
Do we have some volunteers to help make the release on the CRAN side?

**Comment by palday** [comment]
> Do we have some volunteers to help make the release on the CRAN side?

maybe @Non-Contradiction ?

I will also have a bit more time on Friday (15 November).

**Comment by ikosmidis** [comment]
Hi all! Thanks for fixing this. Any updates when this will be on CRAN?

In case someone is planning or doing that already, and just in case you haven't figured this out (and as briefly mentioned earlier), here are some steps of how to go about releasing in CRAN.

If @ChrisRackauckas takes over maintenance, then @ChrisRackauckas must submit the package to CRAN. 

The easiest way forward is to update the DESCRIPTION file with a change of maintainer in the DESCRIPTION file, e.g.
```
Authors@R: c(
    person(given = "Christopher", family = "Rackauckas", email = "accounts@chrisrackauckas.com", role = c("aut", "cre")),
    person(given = "Changcheng", family = "Li", role = "aut", comment = "earlier version by"),
    person(given = "Randy", family = "Lai",  role = "ctb"),
    person(given = "Dmitri", family = "Grominski", role = "ctb"),
    person(given = "Nagi", family - "Teramo", role = "ctb")
    )
```
The above explicitly recognises that @Non-Contradiction produced earlier versions and that @ChrisRackauckas is the current maintainer (see, e.g., https://cran.r-project.org/package=betareg> for an example of how that would look on CRAN pages). It may be worth adding other people who contributed to the release using the "ctb" role. 

Then, you can just use [`devtools::release()`]("https://devtools.r-lib.org/reference/release.html") to submit, which will also guide you to what one can do to minimize the chance of breaking CRAN rules.

When submitted, @Non-Contradiction will receive an email to approve the change of maintainership. 

I am happy to help, but it should be straightforward with the above steps.

**Comment by PallHaraldsson** [comment]
>Any updates when this will be on CRAN?

I don't know about that, but given the holdup here my alternative PR could be merged (it doesn't need to be either or):

https://github.com/JuliaLang/julia/pull/56340#issuecomment-2497991447
>Maybe just merge this, because of the hold-up with the alternative (and since it's approved, and not a problem to have in).

**Comment by marc-milgrom-ncl** [comment]
> In case anyone else is hitting this error:
> 
> ```
> Error: jl_stdout_obj - /home/office/.julia/juliaup/julia-1.11.1+0.x64.linux.gnu/bin/../lib/libjulia.so.1.11: undefined symbol: jl_stdout_obj
> ```
> 
> You'll need to install from the repo until the CRAN package is updated:
> 
> ```
> library(devtools)
> install_github("https://github.com/JuliaInterop/JuliaCall")
> ```
I've installed from the repo and still get the error. It fails devtools::check() unless I specify JULIA_HOME to 1.9. Is the PR merged yet?

**Comment by Non-Contradiction** [comment]
Thanks everyone! It seems to me that the main issue is solved. I will do more test/check for the package and make a release on CRAN next week.

**Comment by ChrisRackauckas** [comment]
> If @ChrisRackauckas takes over maintenance, then @ChrisRackauckas must submit the package to CRAN.

I see, I thought it was the other way around. I thought I needed to be added as a maintainer, and then I could submit to CRAN. So I was waiting on that. Either way @Non-Contradiction it would be helpful to get the CRAN status so we can keep this on-going. It's great work and I don't want it to get lost in the sands of time!

**Comment by ikosmidis** [comment]
Indeed, if things have not changed since the last change of maintenance event I was involved in (~2017), when @ChrisRackauckas submits @Non-Contradiction will get an email with the following content
> Someone has submitted the package cranly to CRAN. You are receiving this email to confirm the submission as the maintainer of this package. To confirm the submission to CRAN, follow or copy & paste the following link into your browser:

After approving the submission, CRAN should come back to @Non-Contradiction and ask about the maintenance change.

If the process has changed then the CRAN team are pretty good in telling authors what should be done.

**Comment by schlichtanders** [comment]
The CRAN release seems to have worked. I am using juliacall via conda/CondaPkg.jl
can someone trigger a release there too?
https://anaconda.org/r/r-juliacall

**Comment by schlichtanders** [comment]
@Non-Contradiction can you help with the anaconda release?

**Comment by Non-Contradiction** [comment]
@schlichtanders I just checked and see that `conda-forge/r-juliacall` is already the 0.17.6 version and is more downloaded, although the `r/r-juliacall` is still the 0.17.5 version. I will check about how to update the `r/r-juliacall` channel.

**Comment by schlichtanders** [comment]
thanks, I indeed was confused by r/r-juliacall and thought that it is not yet available. Great that conda-forge is already released!

**Pull request merged**
